version: '3'
services:
  server:
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=9000
    ports:
      - "9000:9000"
    volumes:
      - ./db:/db
  client:
    build:
        context: ./chat-client
        dockerfile: Dockerfile
    restart: unless-stopped
    ports:
        - "80:80"